### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Onitsukun** [sehaas/yfmos#13]
Hi everyone,
When i install a have an error on the last step:

```
ERROR:` Command errored out with exit status 1:
     command: /home/oni/yfmos/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mu8w8rb9/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mu8w8rb9/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mu8w8rb9/pycurl/pip-egg-info
         cwd: /tmp/pip-install-mu8w8rb9/pycurl/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-mu8w8rb9/pycurl/setup.py", line 222, in configure_unix
        p = subprocess.Popen((self.curl_config(), '--version'),
      File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mu8w8rb9/pycurl/setup.py", line 913, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-mu8w8rb9/pycurl/setup.py", line 582, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-mu8w8rb9/pycurl/setup.py", line 99, in __init__
        self.configure()
      File "/tmp/pip-install-mu8w8rb9/pycurl/setup.py", line 227, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


```

can you help me please

**Comment by Onitsukun** [comment]
so it appear i can't install pycurl... 
i've tried in ubuntu and debian via windows app
and in my ubuntu vm on my unraid server
every time the same error :/ 
i just need a B0 for my gate can someone help me please

**Comment by sehaas** [comment]
Hi @Onitsukun, yes it looks like a problem during pycurl installation.
Maybe this helps https://github.com/pycurl/pycurl/issues/452?
Just to clarify: due to the rolling code you need a new B0 for every command you want so send.
